name: Websitedesign
favicon: null
layout_spectrum: 0.9886043376754969
typography_spectrum: 0.5782924371305853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c2c3c5'
    - '#bc864e'
    - '#926232'
    - '#623d19'
  brandStrength: 0.6168951774016023
  lightness: 0.5473975418135524
  saturation: 0.6799161026719958
  rhythmicContrast: 0.767849424155429
purpose: []
