name: Websitedesign
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.74639
title: The New Age of Websites
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefffa'
    - '#1a1613'
    - '#294b71'
    - '#cdbf9c'
    - '#6795ad'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
