name: Websitedesign
favicon: null
layout_spectrum: 0.74819
typography_spectrum: 0.74639
title: The New Age of Websites
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4a819f'
    - '#a9cde7'
    - '#b6a281'
    - '#384555'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
